"""Unified-diff parsing and change classification.

Two input shapes are supported:

* a full ``git diff`` (``diff --git`` headers) -- what the ``.diff`` media type
  of the GitHub API returns;
* a per-file ``patch`` string -- what ``GET /pulls/{n}/files`` returns.

Besides parsing, this module classifies *what kind of change* each hunk makes
(imports, database access, concurrency, error handling, tests, API surface),
which becomes structured evidence for the reviewer.
"""

from __future__ import annotations

import re
from collections.abc import Iterable
from dataclasses import dataclass, field
from typing import Any, Literal

from app.analyzers.base import (
    AnalysisRequest,
    AnalyzerResult,
    Language,
    RepositoryAnalyzer,
    detect_language,
)

LineKind = Literal["add", "del", "ctx"]
ChangeType = Literal["added", "modified", "removed", "renamed", "copied", "changed"]

_HUNK_RE = re.compile(r"^@@ -(\d+)(?:,(\d+))? \+(\d+)(?:,(\d+))? @@(.*)$")
_DIFF_GIT_RE = re.compile(r"^diff --git a/(?P<a>.+?) b/(?P<b>.+)$")

GENERATED_MARKERS = (
    "@generated",
    "autogenerated",
    "do not edit",
    "code generated by",
)

GENERATED_PATH_PATTERNS = (
    "package-lock.json",
    "yarn.lock",
    "pnpm-lock.yaml",
    "poetry.lock",
    "Pipfile.lock",
    ".min.js",
    ".min.css",
    "_pb2.py",
    ".snap",
)

TEST_PATH_PATTERNS = (
    "test_",
    "_test.",
    "/tests/",
    "\\tests\\",
    "/test/",
    ".test.",
    ".spec.",
    "conftest.py",
    "__tests__",
)


# --------------------------------------------------------------------- signals
SIGNAL_PATTERNS: dict[str, tuple[re.Pattern[str], ...]] = {
    "imports": (
        re.compile(r"^\s*(?:from\s+[\w.]+\s+)?import\s+", re.I),
        re.compile(r"^\s*(?:import|export)\s+.*from\s+['\"]"),
        re.compile(r"require\(['\"]"),
    ),
    "database": (
        re.compile(r"\b(SELECT|INSERT INTO|UPDATE|DELETE FROM|CREATE TABLE|ALTER TABLE)\b", re.I),
        re.compile(r"\b(session|db|conn|cursor)\.(execute|query|add|commit|rollback|delete)\b"),
        re.compile(r"\b(?:prisma|knex|sequelize|mongoose|sqlalchemy)\b", re.I),
        re.compile(r"\.(?:findOne|findMany|createMany|updateMany|deleteMany)\("),
    ),
    "concurrency": (
        re.compile(r"\b(?:async\s+def|await\s+|asyncio\.|threading\.|Thread\(|multiprocessing)\b"),
        re.compile(r"\b(?:Promise\.all|Promise\.race|setTimeout|setInterval|Worker\()"),
        re.compile(r"\b(?:Lock|Semaphore|Mutex|atomic|race)\b"),
    ),
    "error_handling": (
        re.compile(r"^\s*(?:try|except|finally|raise|catch|throw)\b"),
        re.compile(r"\.catch\(|Promise\.reject|process\.exit"),
    ),
    "authentication": (
        re.compile(
            r"\b(?:auth|token|jwt|session|login|logout|password|credential|permission|role|scope)\b",
            re.I,
        ),
    ),
    "network": (
        re.compile(r"\b(?:requests\.|httpx\.|urllib|fetch\(|axios\.|http\.request)\b"),
    ),
    "filesystem": (
        re.compile(r"\b(?:open\(|os\.path|pathlib|shutil|fs\.(?:read|write)|readFile|writeFile)\b"),
    ),
    "subprocess": (
        re.compile(r"\b(?:subprocess|os\.system|os\.popen|exec\(|eval\(|child_process|spawn\()"),
    ),
    "payments": (
        re.compile(r"\b(?:payment|charge|invoice|refund|stripe|billing|checkout|price)\b", re.I),
    ),
    "api_surface": (
        re.compile(r"@(?:app|router|api)\.(?:get|post|put|patch|delete)\b"),
        re.compile(r"\b(?:router|app)\.(?:get|post|put|patch|delete)\("),
        re.compile(r"^\s*(?:export\s+)?(?:async\s+)?function\s+\w+"),
    ),
    "config": (
        re.compile(r"\b(?:os\.environ|getenv|process\.env|settings\.|config\.)\b"),
    ),
    "logging": (
        re.compile(r"\b(?:logger|logging|console\.(?:log|error|warn)|print\()\b"),
    ),
}


@dataclass(slots=True)
class DiffLine:
    kind: LineKind
    content: str
    old_lineno: int | None
    new_lineno: int | None
    position: int  # GitHub diff position (1-based from first @@ of the file)

    @property
    def is_change(self) -> bool:
        return self.kind in ("add", "del")


@dataclass(slots=True)
class DiffHunk:
    old_start: int
    old_count: int
    new_start: int
    new_count: int
    section: str
    lines: list[DiffLine] = field(default_factory=list)

    @property
    def header(self) -> str:
        return f"@@ -{self.old_start},{self.old_count} +{self.new_start},{self.new_count} @@"

    @property
    def added_lines(self) -> list[DiffLine]:
        return [ln for ln in self.lines if ln.kind == "add"]

    @property
    def removed_lines(self) -> list[DiffLine]:
        return [ln for ln in self.lines if ln.kind == "del"]

    def to_text(self, *, max_lines: int = 400) -> str:
        prefix = {"add": "+", "del": "-", "ctx": " "}
        body = [f"{prefix[ln.kind]}{ln.content}" for ln in self.lines[:max_lines]]
        return "\n".join([f"{self.header} {self.section}".rstrip(), *body])


@dataclass(slots=True)
class FileDiff:
    path: str
    previous_path: str | None = None
    change_type: ChangeType = "modified"
    language: Language = Language.UNKNOWN
    hunks: list[DiffHunk] = field(default_factory=list)
    additions: int = 0
    deletions: int = 0
    is_binary: bool = False
    is_generated: bool = False
    is_test: bool = False
    truncated: bool = False
    signals: dict[str, int] = field(default_factory=dict)

    @property
    def added_line_numbers(self) -> set[int]:
        return {
            ln.new_lineno
            for hunk in self.hunks
            for ln in hunk.lines
            if ln.kind == "add" and ln.new_lineno is not None
        }

    @property
    def context_line_numbers(self) -> set[int]:
        return {
            ln.new_lineno
            for hunk in self.hunks
            for ln in hunk.lines
            if ln.new_lineno is not None
        }

    @property
    def changed_ranges(self) -> list[tuple[int, int]]:
        """Contiguous ranges of added lines, used to focus AST analysis."""
        numbers = sorted(self.added_line_numbers)
        if not numbers:
            return []
        ranges: list[tuple[int, int]] = []
        start = prev = numbers[0]
        for number in numbers[1:]:
            if number == prev + 1:
                prev = number
                continue
            ranges.append((start, prev))
            start = prev = number
        ranges.append((start, prev))
        return ranges

    def position_for_line(self, line_number: int) -> int | None:
        for hunk in self.hunks:
            for line in hunk.lines:
                if line.new_lineno == line_number and line.kind in ("add", "ctx"):
                    return line.position
        return None

    def to_text(self, *, max_lines_per_hunk: int = 400) -> str:
        head = f"--- {self.previous_path or self.path}\n+++ {self.path}"
        return "\n".join(
            [head, *[hunk.to_text(max_lines=max_lines_per_hunk) for hunk in self.hunks]]
        )

    def to_summary(self) -> dict[str, Any]:
        return {
            "path": self.path,
            "previous_path": self.previous_path,
            "change_type": self.change_type,
            "language": self.language.value,
            "additions": self.additions,
            "deletions": self.deletions,
            "hunks": len(self.hunks),
            "is_test": self.is_test,
            "is_generated": self.is_generated,
            "is_binary": self.is_binary,
            "truncated": self.truncated,
            "signals": self.signals,
            "changed_ranges": self.changed_ranges,
        }


@dataclass(slots=True)
class DiffAnalysis:
    files: list[FileDiff] = field(default_factory=list)
    truncated: bool = False
    dropped_files: list[str] = field(default_factory=list)

    @property
    def total_additions(self) -> int:
        return sum(f.additions for f in self.files)

    @property
    def total_deletions(self) -> int:
        return sum(f.deletions for f in self.files)

    @property
    def analyzable_files(self) -> list[FileDiff]:
        from app.analyzers.base import ANALYZABLE_LANGUAGES

        return [
            f
            for f in self.files
            if f.language in ANALYZABLE_LANGUAGES and not f.is_binary and not f.is_generated
        ]

    @property
    def test_files(self) -> list[FileDiff]:
        return [f for f in self.files if f.is_test]

    @property
    def source_files(self) -> list[FileDiff]:
        return [f for f in self.files if not f.is_test and not f.is_generated and not f.is_binary]

    def by_path(self, path: str) -> FileDiff | None:
        for file in self.files:
            if file.path == path:
                return file
        return None

    @property
    def aggregate_signals(self) -> dict[str, int]:
        totals: dict[str, int] = {}
        for file in self.files:
            for signal, count in file.signals.items():
                totals[signal] = totals.get(signal, 0) + count
        return totals

    def to_dict(self) -> dict[str, Any]:
        return {
            "files": [f.to_summary() for f in self.files],
            "total_files": len(self.files),
            "total_additions": self.total_additions,
            "total_deletions": self.total_deletions,
            "truncated": self.truncated,
            "dropped_files": self.dropped_files,
            "signals": self.aggregate_signals,
        }


# ------------------------------------------------------------------- parsing
def _classify_path(path: str) -> tuple[bool, bool]:
    lowered = path.replace("\\", "/").lower()
    is_test = any(marker in lowered for marker in TEST_PATH_PATTERNS)
    is_generated = any(marker in lowered for marker in GENERATED_PATH_PATTERNS)
    return is_test, is_generated


def _collect_signals(lines: Iterable[str]) -> dict[str, int]:
    signals: dict[str, int] = {}
    for line in lines:
        for signal, patterns in SIGNAL_PATTERNS.items():
            if any(pattern.search(line) for pattern in patterns):
                signals[signal] = signals.get(signal, 0) + 1
    return signals


def parse_patch(path: str, patch: str | None, *, change_type: ChangeType = "modified",
                previous_path: str | None = None) -> FileDiff:
    """Parse a single-file patch (GitHub ``files`` API shape)."""
    language = detect_language(path)
    is_test, is_generated = _classify_path(path)
    file_diff = FileDiff(
        path=path,
        previous_path=previous_path,
        change_type=change_type,
        language=language,
        is_test=is_test,
        is_generated=is_generated,
        is_binary=patch is None,
    )
    if not patch:
        return file_diff

    position = 0
    hunk: DiffHunk | None = None
    old_lineno = new_lineno = 0

    for raw_line in patch.splitlines():
        match = _HUNK_RE.match(raw_line)
        if match:
            old_start = int(match.group(1))
            old_count = int(match.group(2) or 1)
            new_start = int(match.group(3))
            new_count = int(match.group(4) or 1)
            hunk = DiffHunk(
                old_start=old_start,
                old_count=old_count,
                new_start=new_start,
                new_count=new_count,
                section=(match.group(5) or "").strip(),
            )
            file_diff.hunks.append(hunk)
            old_lineno, new_lineno = old_start, new_start
            position += 1
            continue

        if hunk is None:
            # Content before the first hunk header (e.g. "Binary files differ").
            if raw_line.startswith("Binary files"):
                file_diff.is_binary = True
            continue

        position += 1
        if raw_line.startswith("+"):
            hunk.lines.append(
                DiffLine("add", raw_line[1:], None, new_lineno, position)
            )
            new_lineno += 1
            file_diff.additions += 1
        elif raw_line.startswith("-"):
            hunk.lines.append(
                DiffLine("del", raw_line[1:], old_lineno, None, position)
            )
            old_lineno += 1
            file_diff.deletions += 1
        elif raw_line.startswith("\\"):
            # "\ No newline at end of file" -- not a real diff line.
            position -= 1
        else:
            content = raw_line[1:] if raw_line.startswith(" ") else raw_line
            hunk.lines.append(DiffLine("ctx", content, old_lineno, new_lineno, position))
            old_lineno += 1
            new_lineno += 1

    added_contents = [ln.content for h in file_diff.hunks for ln in h.added_lines]
    file_diff.signals = _collect_signals(added_contents)
    if not file_diff.is_generated:
        file_diff.is_generated = any(
            marker in line.lower() for line in added_contents[:40] for marker in GENERATED_MARKERS
        )
    return file_diff


def parse_unified_diff(diff_text: str) -> DiffAnalysis:
    """Parse a complete ``git diff`` into per-file patches."""
    analysis = DiffAnalysis()
    if not diff_text:
        return analysis

    current_path: str | None = None
    previous_path: str | None = None
    change_type: ChangeType = "modified"
    buffer: list[str] = []

    def flush() -> None:
        nonlocal current_path, previous_path, change_type, buffer
        if current_path is None:
            return
        patch = "\n".join(buffer) if buffer else None
        analysis.files.append(
            parse_patch(
                current_path,
                patch,
                change_type=change_type,
                previous_path=previous_path if previous_path != current_path else None,
            )
        )
        current_path = None
        previous_path = None
        change_type = "modified"
        buffer = []

    for line in diff_text.splitlines():
        header = _DIFF_GIT_RE.match(line)
        if header:
            flush()
            previous_path = header.group("a")
            current_path = header.group("b")
            continue
        if current_path is None:
            continue
        if line.startswith("new file mode"):
            change_type = "added"
            continue
        if line.startswith("deleted file mode"):
            change_type = "removed"
            continue
        if line.startswith("rename from "):
            previous_path = line[len("rename from ") :].strip()
            change_type = "renamed"
            continue
        if line.startswith("rename to "):
            current_path = line[len("rename to ") :].strip()
            continue
        if line.startswith(("index ", "similarity index", "old mode", "new mode", "copy ")):
            continue
        if line.startswith("--- ") or line.startswith("+++ "):
            continue
        if line.startswith("Binary files"):
            buffer.append(line)
            continue
        buffer.append(line)

    flush()
    return analysis


def build_diff_analysis(
    files: list[dict[str, Any]],
    *,
    max_files: int,
    max_total_bytes: int,
) -> DiffAnalysis:
    """Build a :class:`DiffAnalysis` from GitHub ``files`` API entries.

    Large pull requests are truncated deterministically: source files are
    prioritised over tests, tests over generated files, and everything is capped
    so an oversized PR can never blow up context or cost budgets.
    """
    analysis = DiffAnalysis()

    def priority(entry: dict[str, Any]) -> tuple[int, int]:
        path = entry.get("filename", "")
        is_test, is_generated = _classify_path(path)
        language = detect_language(path)
        rank = 0
        if is_generated:
            rank = 3
        elif is_test:
            rank = 2
        elif language == Language.UNKNOWN:
            rank = 1
        changes = int(entry.get("changes") or 0)
        return (rank, -changes)

    ordered = sorted(files, key=priority)
    consumed = 0
    for entry in ordered:
        path = entry.get("filename")
        if not path:
            continue
        if len(analysis.files) >= max_files:
            analysis.truncated = True
            analysis.dropped_files.append(path)
            continue
        patch = entry.get("patch")
        if patch and consumed + len(patch) > max_total_bytes:
            analysis.truncated = True
            analysis.dropped_files.append(path)
            continue
        if patch:
            consumed += len(patch)
        status = str(entry.get("status") or "modified")
        change_type: ChangeType = status if status in {
            "added",
            "modified",
            "removed",
            "renamed",
            "copied",
            "changed",
        } else "modified"  # type: ignore[assignment]
        file_diff = parse_patch(
            path,
            patch,
            change_type=change_type,
            previous_path=entry.get("previous_filename"),
        )
        if not patch:
            file_diff.additions = int(entry.get("additions") or 0)
            file_diff.deletions = int(entry.get("deletions") or 0)
            file_diff.is_binary = bool(entry.get("additions") or entry.get("deletions")) is False
            file_diff.truncated = True
        analysis.files.append(file_diff)

    # Restore a stable, human-friendly ordering for presentation.
    analysis.files.sort(key=lambda f: f.path)
    return analysis


class DiffAnalyzer(RepositoryAnalyzer):
    """Summarises the diff into structured change evidence."""

    name = "diff"

    def analyze(self, request: AnalysisRequest) -> AnalyzerResult:
        diff = request.diff
        by_language: dict[str, int] = {}
        for file in diff.files:
            by_language[file.language.value] = by_language.get(file.language.value, 0) + 1

        largest = sorted(
            diff.files, key=lambda f: f.additions + f.deletions, reverse=True
        )[:5]

        data: dict[str, Any] = {
            "total_files": len(diff.files),
            "total_additions": diff.total_additions,
            "total_deletions": diff.total_deletions,
            "by_language": by_language,
            "signals": diff.aggregate_signals,
            "test_files_changed": [f.path for f in diff.test_files],
            "source_files_changed": [f.path for f in diff.source_files],
            "generated_files_skipped": [f.path for f in diff.files if f.is_generated],
            "binary_files_skipped": [f.path for f in diff.files if f.is_binary],
            "largest_changes": [
                {"path": f.path, "changes": f.additions + f.deletions} for f in largest
            ],
            "truncated": diff.truncated,
            "dropped_files": diff.dropped_files,
            "files": [f.to_summary() for f in diff.files],
        }
        warnings: list[str] = []
        if diff.truncated:
            warnings.append(
                f"Diff truncated: {len(diff.dropped_files)} file(s) excluded from analysis."
            )
        return AnalyzerResult(name=self.name, data=data, warnings=warnings)
