"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-08-31 17:24:36.188082
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.db.types

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('github_installations',
    sa.Column('installation_id', sa.BigInteger(), nullable=False),
    sa.Column('account_login', sa.String(length=200), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=True),
    sa.Column('account_type', sa.String(length=40), nullable=False),
    sa.Column('target_type', sa.String(length=40), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('permissions', app.db.types.JSONType(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('suspended', sa.Boolean(), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_github_installations'))
    )
    with op.batch_alter_table('github_installations', schema=None) as batch_op:
        batch_op.create_index('ix_github_installations_account', ['account_login'], unique=False)
        batch_op.create_index(batch_op.f('ix_github_installations_installation_id'), ['installation_id'], unique=True)

    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('github_user_id', sa.BigInteger(), nullable=True),
    sa.Column('github_login', sa.String(length=120), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_github_login'), ['github_login'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_github_user_id'), ['github_user_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('audit_logs',
    sa.Column('user_id', app.db.types.GUID(), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=True),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('context', app.db.types.JSONType(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=400), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('ix_audit_logs_action', ['action'], unique=False)
        batch_op.create_index('ix_audit_logs_created_at', ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('installation_memberships',
    sa.Column('user_id', app.db.types.GUID(), nullable=False),
    sa.Column('installation_id', app.db.types.GUID(), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['installation_id'], ['github_installations.id'], name=op.f('fk_installation_memberships_installation_id_github_installations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_installation_memberships_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_installation_memberships')),
    sa.UniqueConstraint('user_id', 'installation_id', name='uq_membership_user_installation')
    )
    with op.batch_alter_table('installation_memberships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_installation_memberships_installation_id'), ['installation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_installation_memberships_user_id'), ['user_id'], unique=False)

    op.create_table('oauth_states',
    sa.Column('state', sa.String(length=128), nullable=False),
    sa.Column('user_id', app.db.types.GUID(), nullable=False),
    sa.Column('redirect_to', sa.String(length=500), nullable=True),
    sa.Column('consumed', sa.Boolean(), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_oauth_states_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_oauth_states'))
    )
    with op.batch_alter_table('oauth_states', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_oauth_states_state'), ['state'], unique=True)
        batch_op.create_index(batch_op.f('ix_oauth_states_user_id'), ['user_id'], unique=False)

    op.create_table('repositories',
    sa.Column('github_repo_id', sa.BigInteger(), nullable=False),
    sa.Column('installation_id', app.db.types.GUID(), nullable=False),
    sa.Column('owner', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('full_name', sa.String(length=400), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('default_branch', sa.String(length=200), nullable=False),
    sa.Column('private', sa.Boolean(), nullable=False),
    sa.Column('language', sa.String(length=80), nullable=True),
    sa.Column('html_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['installation_id'], ['github_installations.id'], name=op.f('fk_repositories_installation_id_github_installations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_repositories')),
    sa.UniqueConstraint('github_repo_id', name='uq_repositories_github_repo_id')
    )
    with op.batch_alter_table('repositories', schema=None) as batch_op:
        batch_op.create_index('ix_repositories_full_name', ['full_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_repositories_github_repo_id'), ['github_repo_id'], unique=False)
        batch_op.create_index('ix_repositories_installation_active', ['installation_id', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_repositories_installation_id'), ['installation_id'], unique=False)

    op.create_table('indexed_files',
    sa.Column('repository_id', app.db.types.GUID(), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('commit_sha', sa.String(length=64), nullable=False),
    sa.Column('language', sa.String(length=40), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], name=op.f('fk_indexed_files_repository_id_repositories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_indexed_files')),
    sa.UniqueConstraint('repository_id', 'file_path', name='uq_indexed_file_repo_path')
    )
    with op.batch_alter_table('indexed_files', schema=None) as batch_op:
        batch_op.create_index('ix_indexed_files_repo', ['repository_id'], unique=False)

    op.create_table('pull_requests',
    sa.Column('repository_id', app.db.types.GUID(), nullable=False),
    sa.Column('github_pr_id', sa.BigInteger(), nullable=True),
    sa.Column('github_pr_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=600), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=200), nullable=False),
    sa.Column('author_avatar_url', sa.String(length=500), nullable=True),
    sa.Column('base_branch', sa.String(length=300), nullable=True),
    sa.Column('head_branch', sa.String(length=300), nullable=True),
    sa.Column('base_sha', sa.String(length=64), nullable=False),
    sa.Column('head_sha', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('draft', sa.Boolean(), nullable=False),
    sa.Column('html_url', sa.String(length=600), nullable=True),
    sa.Column('additions', sa.Integer(), nullable=False),
    sa.Column('deletions', sa.Integer(), nullable=False),
    sa.Column('changed_files', sa.Integer(), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], name=op.f('fk_pull_requests_repository_id_repositories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pull_requests')),
    sa.UniqueConstraint('repository_id', 'github_pr_number', name='uq_pr_repo_number')
    )
    with op.batch_alter_table('pull_requests', schema=None) as batch_op:
        batch_op.create_index('ix_pull_requests_head_sha', ['head_sha'], unique=False)
        batch_op.create_index('ix_pull_requests_repo_number', ['repository_id', 'github_pr_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_pull_requests_repository_id'), ['repository_id'], unique=False)
        batch_op.create_index('ix_pull_requests_state', ['state'], unique=False)

    op.create_table('repository_indexes',
    sa.Column('repository_id', app.db.types.GUID(), nullable=False),
    sa.Column('commit_sha', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('files_indexed', sa.Integer(), nullable=False),
    sa.Column('files_skipped', sa.Integer(), nullable=False),
    sa.Column('chunks_indexed', sa.Integer(), nullable=False),
    sa.Column('chunks_deleted', sa.Integer(), nullable=False),
    sa.Column('incremental', sa.Boolean(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], name=op.f('fk_repository_indexes_repository_id_repositories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_repository_indexes'))
    )
    with op.batch_alter_table('repository_indexes', schema=None) as batch_op:
        batch_op.create_index('ix_repository_indexes_repo_commit', ['repository_id', 'commit_sha'], unique=False)
        batch_op.create_index(batch_op.f('ix_repository_indexes_repository_id'), ['repository_id'], unique=False)
        batch_op.create_index('ix_repository_indexes_status', ['status'], unique=False)

    op.create_table('repository_settings',
    sa.Column('repository_id', app.db.types.GUID(), nullable=False),
    sa.Column('auto_review_enabled', sa.Boolean(), nullable=False),
    sa.Column('review_on_open', sa.Boolean(), nullable=False),
    sa.Column('review_on_synchronize', sa.Boolean(), nullable=False),
    sa.Column('publish_to_github', sa.Boolean(), nullable=False),
    sa.Column('min_severity', sa.String(length=20), nullable=False),
    sa.Column('max_files_per_review', sa.Integer(), nullable=False),
    sa.Column('min_confidence', sa.Float(), nullable=False),
    sa.Column('excluded_paths', app.db.types.JSONType(), nullable=False),
    sa.Column('enabled_analyzers', app.db.types.JSONType(), nullable=False),
    sa.Column('llm_model', sa.String(length=120), nullable=True),
    sa.Column('review_event', sa.String(length=20), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], name=op.f('fk_repository_settings_repository_id_repositories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_repository_settings'))
    )
    with op.batch_alter_table('repository_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_repository_settings_repository_id'), ['repository_id'], unique=True)

    op.create_table('review_runs',
    sa.Column('pull_request_id', app.db.types.GUID(), nullable=False),
    sa.Column('commit_sha', sa.String(length=64), nullable=False),
    sa.Column('trigger', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('stage', sa.String(length=60), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_band', sa.String(length=20), nullable=True),
    sa.Column('risk_factors', app.db.types.JSONType(), nullable=True),
    sa.Column('files_analyzed', sa.Integer(), nullable=False),
    sa.Column('files_skipped', sa.Integer(), nullable=False),
    sa.Column('findings_count', sa.Integer(), nullable=False),
    sa.Column('suppressed_count', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('analysis', app.db.types.JSONType(), nullable=True),
    sa.Column('static_findings', app.db.types.JSONType(), nullable=True),
    sa.Column('context_stats', app.db.types.JSONType(), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('github_review_id', sa.BigInteger(), nullable=True),
    sa.Column('github_review_url', sa.String(length=600), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['pull_request_id'], ['pull_requests.id'], name=op.f('fk_review_runs_pull_request_id_pull_requests'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_runs')),
    sa.UniqueConstraint('pull_request_id', 'commit_sha', name='uq_review_run_pr_commit')
    )
    with op.batch_alter_table('review_runs', schema=None) as batch_op:
        batch_op.create_index('ix_review_runs_commit_sha', ['commit_sha'], unique=False)
        batch_op.create_index('ix_review_runs_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_review_runs_pr', ['pull_request_id'], unique=False)
        batch_op.create_index('ix_review_runs_status', ['status'], unique=False)

    op.create_table('findings',
    sa.Column('review_run_id', app.db.types.GUID(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=True),
    sa.Column('start_line', sa.Integer(), nullable=True),
    sa.Column('end_line', sa.Integer(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=400), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('code_snippet', sa.Text(), nullable=True),
    sa.Column('suggested_fix', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('confidence_label', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('rule_id', sa.String(length=120), nullable=True),
    sa.Column('references', app.db.types.JSONType(), nullable=True),
    sa.Column('related_symbols', app.db.types.JSONType(), nullable=True),
    sa.Column('historical_context', app.db.types.JSONType(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('resolved_by_id', app.db.types.GUID(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['users.id'], name=op.f('fk_findings_resolved_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['review_run_id'], ['review_runs.id'], name=op.f('fk_findings_review_run_id_review_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_findings'))
    )
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.create_index('ix_findings_category', ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_fingerprint'), ['fingerprint'], unique=False)
        batch_op.create_index('ix_findings_review_run', ['review_run_id'], unique=False)
        batch_op.create_index('ix_findings_run_file', ['review_run_id', 'file_path'], unique=False)
        batch_op.create_index('ix_findings_severity', ['severity'], unique=False)
        batch_op.create_index('ix_findings_status', ['status'], unique=False)

    op.create_table('llm_usage',
    sa.Column('review_run_id', app.db.types.GUID(), nullable=True),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('operation', sa.String(length=60), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=False),
    sa.Column('cached', sa.Boolean(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['review_run_id'], ['review_runs.id'], name=op.f('fk_llm_usage_review_run_id_review_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_llm_usage'))
    )
    with op.batch_alter_table('llm_usage', schema=None) as batch_op:
        batch_op.create_index('ix_llm_usage_run', ['review_run_id'], unique=False)

    op.create_table('webhook_deliveries',
    sa.Column('delivery_id', sa.String(length=120), nullable=False),
    sa.Column('event', sa.String(length=60), nullable=False),
    sa.Column('action', sa.String(length=60), nullable=True),
    sa.Column('installation_id', sa.BigInteger(), nullable=True),
    sa.Column('repository_full_name', sa.String(length=400), nullable=True),
    sa.Column('pr_number', sa.Integer(), nullable=True),
    sa.Column('head_sha', sa.String(length=64), nullable=True),
    sa.Column('accepted', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('review_run_id', app.db.types.GUID(), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['review_run_id'], ['review_runs.id'], name=op.f('fk_webhook_deliveries_review_run_id_review_runs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_webhook_deliveries')),
    sa.UniqueConstraint('delivery_id', name='uq_webhook_delivery_id')
    )
    with op.batch_alter_table('webhook_deliveries', schema=None) as batch_op:
        batch_op.create_index('ix_webhook_deliveries_event', ['event'], unique=False)

    op.create_table('review_comments',
    sa.Column('review_run_id', app.db.types.GUID(), nullable=False),
    sa.Column('finding_id', app.db.types.GUID(), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=True),
    sa.Column('line_number', sa.Integer(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('github_comment_id', sa.BigInteger(), nullable=True),
    sa.Column('github_url', sa.String(length=600), nullable=True),
    sa.Column('delivered', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], name=op.f('fk_review_comments_finding_id_findings'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['review_run_id'], ['review_runs.id'], name=op.f('fk_review_comments_review_run_id_review_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_comments'))
    )
    with op.batch_alter_table('review_comments', schema=None) as batch_op:
        batch_op.create_index('ix_review_comments_run', ['review_run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_comments', schema=None) as batch_op:
        batch_op.drop_index('ix_review_comments_run')

    op.drop_table('review_comments')
    with op.batch_alter_table('webhook_deliveries', schema=None) as batch_op:
        batch_op.drop_index('ix_webhook_deliveries_event')

    op.drop_table('webhook_deliveries')
    with op.batch_alter_table('llm_usage', schema=None) as batch_op:
        batch_op.drop_index('ix_llm_usage_run')

    op.drop_table('llm_usage')
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.drop_index('ix_findings_status')
        batch_op.drop_index('ix_findings_severity')
        batch_op.drop_index('ix_findings_run_file')
        batch_op.drop_index('ix_findings_review_run')
        batch_op.drop_index(batch_op.f('ix_findings_fingerprint'))
        batch_op.drop_index('ix_findings_category')

    op.drop_table('findings')
    with op.batch_alter_table('review_runs', schema=None) as batch_op:
        batch_op.drop_index('ix_review_runs_status')
        batch_op.drop_index('ix_review_runs_pr')
        batch_op.drop_index('ix_review_runs_created_at')
        batch_op.drop_index('ix_review_runs_commit_sha')

    op.drop_table('review_runs')
    with op.batch_alter_table('repository_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_repository_settings_repository_id'))

    op.drop_table('repository_settings')
    with op.batch_alter_table('repository_indexes', schema=None) as batch_op:
        batch_op.drop_index('ix_repository_indexes_status')
        batch_op.drop_index(batch_op.f('ix_repository_indexes_repository_id'))
        batch_op.drop_index('ix_repository_indexes_repo_commit')

    op.drop_table('repository_indexes')
    with op.batch_alter_table('pull_requests', schema=None) as batch_op:
        batch_op.drop_index('ix_pull_requests_state')
        batch_op.drop_index(batch_op.f('ix_pull_requests_repository_id'))
        batch_op.drop_index('ix_pull_requests_repo_number')
        batch_op.drop_index('ix_pull_requests_head_sha')

    op.drop_table('pull_requests')
    with op.batch_alter_table('indexed_files', schema=None) as batch_op:
        batch_op.drop_index('ix_indexed_files_repo')

    op.drop_table('indexed_files')
    with op.batch_alter_table('repositories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_repositories_installation_id'))
        batch_op.drop_index('ix_repositories_installation_active')
        batch_op.drop_index(batch_op.f('ix_repositories_github_repo_id'))
        batch_op.drop_index('ix_repositories_full_name')

    op.drop_table('repositories')
    with op.batch_alter_table('oauth_states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oauth_states_user_id'))
        batch_op.drop_index(batch_op.f('ix_oauth_states_state'))

    op.drop_table('oauth_states')
    with op.batch_alter_table('installation_memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_installation_memberships_user_id'))
        batch_op.drop_index(batch_op.f('ix_installation_memberships_installation_id'))

    op.drop_table('installation_memberships')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index('ix_audit_logs_created_at')
        batch_op.drop_index('ix_audit_logs_action')

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_github_user_id'))
        batch_op.drop_index(batch_op.f('ix_users_github_login'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('github_installations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_github_installations_installation_id'))
        batch_op.drop_index('ix_github_installations_account')

    op.drop_table('github_installations')
    # ### end Alembic commands ###
